POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "user",
  "email": "user@test.com",
  "password": "123456"
}

### login as admin
# @name login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "mohamed@test.com",
  "password": "123456"
}

### login as user
# @name login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "123456"
}

###
@authToken = {{login.response.body.data.token}}
GET http://localhost:5000/api/dashboard/stats
Authorization: Bearer {{authToken}}
###
